trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  sonarcloud.organization: 'kevinduran09' 
  sonarcloud.projectKey: 'Kevinduran09_Repositorio-Proyecto-Frumusa'       
  SONAR_TOKEN: $(SONAR_TOKEN)  # Referencia a la variable secreta

steps:
- script: |
    dotnet tool install --global dotnet-sonarscanner
  displayName: "Instalar SonarScanner (solo para .NET)"
  # Si usas JS/CSS, omite este paso y usa el siguiente.

- task: SonarCloudPrepare@1
  inputs:
    sonarCloudToken: '$(SONAR_TOKEN)'  # Usa la variable secreta aquí
    organization: '$(sonarcloud.organization)'
    scannerMode: 'CLI'
    projectKey: '$(sonarcloud.projectKey)'
    extraProperties: |
      sonar.sources=./

- script: echo "Análisis estático (no hay compilación)"  # Opcional para JS/CSS

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1