trigger:
- main

pool:
  name: 'Default'  # Usa tu agente auto-hospedado

variables:
  sonarcloud.organization: 'kevinduran09'
  sonarcloud.projectKey: 'Kevinduran09_Repositorio-Proyecto-Frumusa'
  SONAR_TOKEN: $(SONAR_TOKEN)  # Variable secreta definida en Azure DevOps

steps:
# Paso 1: Configurar el análisis (no requiere Java ni instalación manual)
- task: SonarCloudPrepare@1
  inputs:
    sonarCloudToken: '$(SONAR_TOKEN)'
    organization: '$(sonarcloud.organization)'
    scannerMode: 'CLI'
    projectKey: '$(sonarcloud.projectKey)'
    extraProperties: |
      sonar.sources=./
      sonar.exclusions=**/*.sql  # Opcional: excluir archivos SQL
      sonar.javascript.environments=chrome,node  # Config específica para JS
      sonar.css.file.suffixes=.css,.scss,.less  # Config para CSS

# Paso 2: Ejecutar análisis estático (sin compilación)
- script: |
    echo "Analizando archivos JS/CSS..."
    # No necesitas comandos de build para JS/CSS estáticos
  displayName: 'Ejecutar análisis'

# Paso 3: Publicar resultados en SonarCloud
- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'
- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
