name: SonarCloud Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  analyze:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Versión actualizada

      # Configura Java (requerido para SonarScanner)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # 👇 Acción actualizada (reemplazo directo)
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token de SonarCloud
          GITHUB_TOKEN: ${{ github.token }}  # Token automático de GitHub
        with:
          args: >
            -Dsonar.projectKey=Kevinduran09_Repositorio-Proyecto-Frumusa
            -Dsonar.organization=Kevinduran09
            -Dsonar.branch.name=main
            -Dsonar.qualitygate.wait=true  # Espera el resultado del Quality Gate
            -Dsonar.scm.provider=git
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=sql,js,css
            -Dsonar.sql.dialect=oracle